### ISSUE TITLE
How do I escape a whitespace in Gherkin ?

### ISSUE THREAD

**Issue by vartikaz-repo** [cucumber-attic/gherkin#261]
`Then verify the below mentioned strings against data in application  
   |   Here is my String|`

My data table has an element with space in the beginning which Gherkin  or cucumber strips while reading. Causing my test to fail. 

I've tried backslash(\), slash(/), single quotes and double quotes none of which work.

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
